version: '3.9'

services:
  rustapp:
    container_name: rustapp
    image: vendor00001/petclinic
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pet_clinic
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#    ports:
#      - '5432:5432'
    volumes:
      - ./database/create_postgres.sql:/docker-entrypoint-initdb.d/create_postgres.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
