apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: petclinic-
namespace: petclinic
resources:
  - namespace.yaml
  - db-deployment.yml
  - db-service.yml
  - petclinic-deployment.yml
  - petclinic-service.yml
