// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDate;
use serde::{Serialize, Deserialize};
// use diesel::prelude::*;


#[derive(Serialize, Deserialize, Debug)]
pub struct Appointment {
    pub id: Option<i32>,
    pub date: Option<NaiveDate>,
    pub veterinarian: i32,
    pub petowner: i32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Pet {
    pub id: Option<i32>,
    pub name: String,
    pub breed: Option<String>,
    pub age: Option<i32>,
    pub owner: Option<i32>,
    pub flag_removed: bool,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Petowner {
    pub id: Option<i32>,
    pub name: String,
    pub birth_date: Option<NaiveDate>,
    pub email: String,
    pub phone: Option<String>,
    pub address: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Treatment {
    pub id: i32,     // id: Option<i32>, treatment_payload
    pub description: String,
    pub pet: i32,
    pub veterinarian: i32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Vaccination {
    pub id: i32,     // id: Option<i32>, vaccination_payload
    pub description: String,
    pub pet: i32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Veterinarian {
    pub id: i32,     // id: Option<i32>, veterinarian_payload
    pub name: String,
    pub inscricao_crmv: String,
}
